name: battery
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alsa-lib=1.2.14
  - annotated-types=0.7.0
  - anyio=4.9.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - boltons=24.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cachecontrol=0.14.3
  - cachecontrol-with-filecache=0.14.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-default-group=1.2.4
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - conda-lock=3.0.2
  - contourpy=1.3.2
  - cpython=3.12.10
  - crashtest=0.4.1
  - cryptography=45.0.3
  - cuda-version=12.9
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - distlib=0.3.9
  - double-conversion=3.3.1
  - dulwich=0.22.8
  - ensureconda=1.4.7
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.1
  - fqdn=1.5.1
  - freetype=2.13.3
  - gitdb=4.0.12
  - gitpython=3.1.44
  - graphite2=1.3.13
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imbalanced-learn=0.13.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.9.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keyring=25.6.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.5
  - libclang13=20.1.5
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.2
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - miceforest=5.6.2
  - mistune=3.1.3
  - more-itertools=10.7.0
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.26.6.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkginfo=1.12.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - polars=1.30.0
  - polars-default=1.30.0
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.0.2
  - pycparser=2.22
  - pydantic=2.11.4
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyproject_hooks=1.2.0
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.12.10
  - python-blosc=1.11.3
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-gil=3.12.10
  - python-installer=0.7.0
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - ruamel.yaml=0.18.11
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - secretstorage=3.3.3
  - semver=3.0.4
  - send2trash=1.8.3
  - setuptools=80.8.0
  - shap=0.47.2
  - shellingham=1.5.4
  - six=1.17.0
  - sklearn-compat=0.1.3
  - slicer=0.0.8
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tomlkit=0.13.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trove-classifiers=2025.5.9.12
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.13.2
  - typing-inspection=0.4.1
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - virtualenv=20.31.2
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgboost=3.0.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - dragon-ml-toolbox==1.4.7
